name: periodic_primitives
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
  - anaconda
dependencies:
  - python=3.10  
  - pip
  - imageio
  - numpy
  - pytorch=2.1.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-image
  - scipy
  - tqdm
  - typing_extensions
  - pip:
      - matplotlib
      - oauthlib
      - packaging
      - CUDA_modules/PeriodicPrimitivesCUDA
      - tensorboard
      - torchmetrics
      - lpips
      - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
      - av
      - imageio[ffmpeg]
