name: periodic_primitives
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - imageio
  - numpy
  - python=3.7
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - scikit-image
  - scipy
  - tqdm=4.66
  - typing_extensions=4.7.1
  - pip:
      - matplotlib==3.5.3
      - oauthlib==3.2.2
      - packaging==23.2
      - CUDA_modules/PeriodicPrimitivesCUDA
      - tensorboard==2.11.2
      - torchmetrics==0.11.4
